import { chromium } from 'playwright-core';
import fs from 'node:fs';
import path from 'node:path';
const url=process.env.PREVIEW_URL,out=process.argv[2]||'work/fullsite-v92',exe=process.env.CHROME_BIN;
if(!url||!exe)throw new Error('PREVIEW_URL and CHROME_BIN required');fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:exe,args:['--no-sandbox','--disable-dev-shm-usage','--ignore-gpu-blocklist','--enable-webgl','--use-gl=angle','--use-angle=swiftshader']});
const report={url,views:[]};
for(const view of [{name:'desktop',width:1600,height:900},{name:'mobile',width:390,height:844}]){
 const ctx=await browser.newContext({viewport:{width:view.width,height:view.height},deviceScaleFactor:1});const page=await ctx.newPage();const errors=[],failed=[],responses=[];
 page.on('console',m=>{if(m.type()==='error')errors.push('console: '+m.text())});page.on('pageerror',e=>errors.push('pageerror: '+e.message));page.on('requestfailed',r=>failed.push({url:r.url(),error:r.failure()?.errorText||''}));page.on('response',r=>{const u=r.url();if(u.includes('aist-fast')||u.includes('aist-film')||u.includes('process-engine'))responses.push({url:u,status:r.status()})});
 const navStart=Date.now();await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForSelector('a[href="/projects/aist/"]',{timeout:30000});
 await page.waitForFunction(()=>performance.getEntriesByType('resource').filter(x=>x.name.includes('/aist-fast/')).length>=4,{timeout:10000});await page.waitForTimeout(150);const preloadAt=Date.now()-navStart;const preload=await page.evaluate(()=>performance.getEntriesByType('resource').filter(x=>x.name.includes('/aist-fast/')).map(x=>({name:x.name.split('/').pop(),duration:Math.round(x.duration),transferSize:x.transferSize,encodedBodySize:x.encodedBodySize})));await page.screenshot({path:path.join(out,view.name+'-home.png')});
 const clickAt=Date.now();await page.locator('a[href="/projects/aist/"]').first().click();await page.waitForTimeout(5000);const diag=await page.evaluate(()=>({path:location.pathname,href:location.href,filmExists:!!document.getElementById('aist-film-v92'),filmReady:document.getElementById('aist-film-v92')?.dataset.assetReady||'',loaderFlag:!!window.__TIMENTI_AIST_V92_SITE__,engineFlag:!!window.__TIMENTI_PROCESS_ENGINE_V92_FULL__,appText:(document.getElementById('app')?.innerText||'').slice(0,300),scripts:[...document.scripts].map(s=>s.src).filter(Boolean).filter(x=>x.includes('aist')||x.includes('process')),links:[...document.querySelectorAll('link[rel=stylesheet]')].map(x=>x.href).filter(x=>x.includes('aist'))}));const aistReadyAfterClick=Date.now()-clickAt;await page.screenshot({path:path.join(out,view.name+'-after-click.png')});report.views.push({...view,preloadAt,aistReadyAfterClick,preload,diag,errors,failed,responses});await ctx.close();
}
await browser.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exit(0);
